name: Deploy

# https://github.com/nyakaz73/heroku-django-deploy/blob/master/.github/workflows/main.yml
# https://github.com/marketplace/actions/deploy-to-heroku#deploy-subdirectory
# https://github.com/nyakaz73/heroku-django-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./backend
jobs:
  heroku_git_deploy_job:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy django to heroku
          uses: nyakaz73/heroku-django-deploy@v0.68
          with: 
            heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: "israelias.js@gmail.com"
            working-directory: ./backend
            use_git: true
            force_push: true

          #Use the output from the hello step
        - name: Get the output status
          run: echo "${{ steps.deploy.outputs.status }}"
        - name: Getting the files in directory
          run: pwd