name: Deploy Backend

# https://github.com/nyakaz73/heroku-django-deploy/blob/master/.github/workflows/main.yml
# https://github.com/marketplace/actions/deploy-to-heroku#deploy-subdirectory
# https://github.com/nyakaz73/heroku-django-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# defaults:
#   run:
#     working-directory: ./backend
jobs:

  Backend_Deploy:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy django to heroku
          uses: nyakaz73/heroku-django-deploy@v0.68
          with: 
            heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: "israelias.js@gmail.com"
            working-directory: ./backend
            use_git: true
            force_push: true

          #Use the output from the hello step
        - name: Get the output status
          run: echo "${{ steps.deploy.outputs.status }}"
        - name: Getting the files in directory
          run: pwd

  Expo_Web_Build:
      name: Export a an Expo web build for Vercel deployment
      runs-on: ubuntu-latest
      needs: Backend_Deploy
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - uses: expo/expo-github-action@v5
          with:
            expo-version: 4.x
            token: ${{ secrets.EXPO_TOKEN }}
            # expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
            # expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
            expo-cache: true
            working-directory: ./frontend-web
        - run: yarn install
        - run: expo build:web

  Frontend_Deploy:
      name: Deploy to Frontend To Vercel
      runs-on: ubuntu-latest
      needs: Expo_Web_Build
      steps:
        - uses: actions/checkout@v2
        - uses: amondnet/vercel-action@v20
          with:
            vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
            # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
            vercel-args: '--prod' #Optional
            vercel-org-id: ${{ secrets.ORG_ID}}  #Required
            vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
            working-directory: ./frontend-web
    